In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read pkl file
pkl_path = 'academic_test.pkl'
pkl = pd.read_pickle(pkl_path)
df = pd.DataFrame(pkl)
df['improved_qn'] = np.nan

In [3]:
def inspect_row(df, row_index):
    print('---------------------')
    print(f'Question {row_index}')
    print(f'Original Question: {df["text"].iloc[row_index]}')
    print(f'Query: {df["query"].iloc[row_index]}')


def insert_modified_question(df, row_index, question):
    
    df['improved_qn'].iloc[row_index] = question
    # print(f'Original Question: {df["text"].iloc[row_index]}')
    # print(f'Query: {df["query"].iloc[row_index]}')
    print(f'Improved Question: {df["improved_qn"].iloc[row_index]}')

## Instruction for re-writing question

- inspect_row(df, index): allows you to check the original question
- insert_modified_question(df, index, improved_question): allows you to insert your improved question into the dataframe

Everyone will need to do 8 queries.

Some hints:

I used GPT4.0 to help me do this task and I did some manual check afterwards.

This is my prompt:

'''
Hi, could I give you a SQL query and you help me to improve its corresponding natural language question or instructions? For example:

- Original Question: return me the year of Making database systems usable .
- Query: SELECT PUBLICATIONalias0.YEAR FROM PUBLICATION AS PUBLICATIONalias0 WHERE PUBLICATIONalias0.TITLE = "Making database systems usable" ;
- Improved Question: return me the year of the publication of the paper with title "Making database systems usable"

The original question is not super clear about what it wants, the improved question clarifies.
'''

In [4]:
# Kangan
inspect_row(df, 0)
insert_modified_question(df, 0, 'return me the year of the publication of the paper with title "Making database systems usable"')

inspect_row(df, 1)
insert_modified_question(df, 1, 'return me all the titles of the paper after year 2000')

inspect_row(df, 2)
insert_modified_question(df, 2, 'return me all the keywords')

inspect_row(df, 3)
insert_modified_question(df, 3, 'return me the reference number of the paper with title "Making database systems usable"')

inspect_row(df, 4)
insert_modified_question(df, 4, 'return me the author name who have papers in VLDB conference in 2002 along with conference name, publication and writes.')

inspect_row(df, 5)
insert_modified_question(df, 5, 'return me the research domain associated with the PVLDB journal')

inspect_row(df, 6)
insert_modified_question(df, 6, 'return me the journals that have published papers authored by "H. V. Jagadish"')

inspect_row(df, 7)
insert_modified_question(df, 7, 'return me list the titles of papers published in the PVLDB journal after the year 2000?')

---------------------
Question 0
Original Question: return me the year of Making database systems usable .
Query: SELECT PUBLICATIONalias0.YEAR FROM PUBLICATION AS PUBLICATIONalias0 WHERE PUBLICATIONalias0.TITLE = "Making database systems usable" ;
Improved Question: return me the year of the publication of the paper with title "Making database systems usable"
---------------------
Question 1
Original Question: return me the papers after 2000 .
Query: SELECT PUBLICATIONalias0.TITLE FROM PUBLICATION AS PUBLICATIONalias0 WHERE PUBLICATIONalias0.YEAR > 2000 ;
Improved Question: return me all the titles of the paper after year 2000
---------------------
Question 2
Original Question: return me all the keywords .
Query: SELECT KEYWORDalias0.KEYWORD FROM KEYWORD AS KEYWORDalias0 ;
Improved Question: return me all the keywords
---------------------
Question 3
Original Question: return me the references of Making database systems usable .
Query: SELECT PUBLICATIONalias0.REFERENCE_NUM FROM PUBLICATION AS PUBLICATIONalias0 WHERE PUBLICATIONalias0.TITLE = "Making database systems usable" ;
Improved Question: return me the reference number of the paper with title "Making database systems usable"
---------------------
Question 4
Original Question: return me the authors who have papers in VLDB conference in 2002 .
Query: SELECT AUTHORalias0.NAME FROM AUTHOR AS AUTHORalias0 , CONFERENCE AS CONFERENCEalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE CONFERENCEalias0.NAME = "VLDB" AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID AND PUBLICATIONalias0.YEAR = 2002 AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the author name who have papers in VLDB conference in 2002 along with conference name, publication and writes.
---------------------
Question 5
Original Question: return me the area of PVLDB .
Query: SELECT DOMAINalias0.NAME FROM DOMAIN AS DOMAINalias0 , DOMAIN_JOURNAL AS DOMAIN_JOURNALalias0 , JOURNAL AS JOURNALalias0 WHERE DOMAINalias0.DID = DOMAIN_JOURNALalias0.DID AND JOURNALalias0.JID = DOMAIN_JOURNALalias0.JID AND JOURNALalias0.NAME = "PVLDB" ;
Improved Question: return me the research domain associated with the PVLDB journal
---------------------
Question 6
Original Question: return me the journals, which have papers by H. V. Jagadish .
Query: SELECT JOURNALalias0.NAME FROM AUTHOR AS AUTHORalias0 , JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the journals that have published papers authored by "H. V. Jagadish"
---------------------
Question 7
Original Question: return me the papers on PVLDB after 2000 .
Query: SELECT PUBLICATIONalias0.TITLE FROM JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.YEAR > 2000 ;
Improved Question: return me list the titles of papers published in the PVLDB journal after the year 2000?

/var/folders/l5/2302s0j90898y2c73n3g1wmr0000gn/T/ipykernel_13681/1462379669.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['improved_qn'].iloc[row_index] = question

In [5]:
# Ruiyang 
inspect_row(df, 8)
insert_modified_question(df, 8, 'return me the titles of papers authored by "H. V. Jagadish" that were published after the year 2000.')

inspect_row(df, 9)
insert_modified_question(df, 9, 'return me the keywords associated with the publication titled "Making database systems usable"')

inspect_row(df, 10)
insert_modified_question(df, 10, 'return me the keywords associated with the publications authored by "H. V. Jagadish"')

inspect_row(df, 11)
insert_modified_question(df, 11, 'return me all the author names in organisation "University of Michigan"')

inspect_row(df, 12)
insert_modified_question(df, 12, 'return me the name of authors specialising in the domain of "Databases" at the orgnisation "University of Michigan"')

inspect_row(df, 13)
insert_modified_question(df, 13, 'return me all the titles of papers published in the PVLDB journal by authors from the University of Michigan')

inspect_row(df, 14)
insert_modified_question(df, 14, 'return me the titles of papers within the research domain "Databases" that have received more than 200 citations')

inspect_row(df, 15)
insert_modified_question(df, 15, 'return me titles of papers authored by "H. V. Jagadish" that have received more than 200 citations')

---------------------
Question 8
Original Question: return me the papers by H. V. Jagadish after 2000 .
Query: SELECT PUBLICATIONalias0.TITLE FROM AUTHOR AS AUTHORalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.YEAR > 2000 AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the titles of papers authored by "H. V. Jagadish" that were published after the year 2000.
---------------------
Question 9
Original Question: return me the keywords of Making database systems usable .
Query: SELECT KEYWORDalias0.KEYWORD FROM KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 WHERE PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID AND PUBLICATIONalias0.TITLE = "Making database systems usable" ;
Improved Question: return me the keywords associated with the publication titled "Making database systems usable"
---------------------
Question 10
Original Question: return me the keywords related to H. V. Jagadish .
Query: SELECT KEYWORDalias0.KEYWORD FROM AUTHOR AS AUTHORalias0 , KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the keywords associated with the publications authored by "H. V. Jagadish"
---------------------
Question 11
Original Question: return me all the researchers in University of Michigan .
Query: SELECT AUTHORalias0.NAME FROM AUTHOR AS AUTHORalias0 , ORGANIZATION AS ORGANIZATIONalias0 WHERE ORGANIZATIONalias0.NAME = "University of Michigan" AND ORGANIZATIONalias0.OID = AUTHORalias0.OID ;
Improved Question: return me all the author names in organisation "University of Michigan"
---------------------
Question 12
Original Question: return me all the researchers in Databases area in University of Michigan .
Query: SELECT AUTHORalias0.NAME FROM AUTHOR AS AUTHORalias0 , DOMAIN AS DOMAINalias0 , DOMAIN_AUTHOR AS DOMAIN_AUTHORalias0 , ORGANIZATION AS ORGANIZATIONalias0 WHERE DOMAIN_AUTHORalias0.AID = AUTHORalias0.AID AND DOMAINalias0.DID = DOMAIN_AUTHORalias0.DID AND DOMAINalias0.NAME = "Databases" AND ORGANIZATIONalias0.NAME = "University of Michigan" AND ORGANIZATIONalias0.OID = AUTHORalias0.OID ;
Improved Question: return me the name of authors specialising in the domain of "Databases" at the orgnisation "University of Michigan"
---------------------
Question 13
Original Question: return me all the papers in PVLDB in University of Michigan .
Query: SELECT PUBLICATIONalias0.TITLE FROM AUTHOR AS AUTHORalias0 , JOURNAL AS JOURNALalias0 , ORGANIZATION AS ORGANIZATIONalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND ORGANIZATIONalias0.NAME = "University of Michigan" AND ORGANIZATIONalias0.OID = AUTHORalias0.OID AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me all the titles of papers published in the PVLDB journal by authors from the University of Michigan
---------------------
Question 14
Original Question: return me the paper in Databases area with more than 200 citations .
Query: SELECT PUBLICATIONalias0.TITLE FROM DOMAIN AS DOMAINalias0 , DOMAIN_PUBLICATION AS DOMAIN_PUBLICATIONalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE DOMAINalias0.DID = DOMAIN_PUBLICATIONalias0.DID AND DOMAINalias0.NAME = "Databases" AND PUBLICATIONalias0.CITATION_NUM > 200 AND PUBLICATIONalias0.PID = DOMAIN_PUBLICATIONalias0.PID ;
Improved Question: return me the titles of papers within the research domain "Databases" that have received more than 200 citations
---------------------
Question 15
Original Question: return me the paper by H. V. Jagadish with more than 200 citations .
Query: SELECT PUBLICATIONalias0.TITLE FROM AUTHOR AS AUTHORalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.CITATION_NUM > 200 AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me titles of papers authored by "H. V. Jagadish" that have received more than 200 citations

In [6]:
# Tian

inspect_row(df, 16)
insert_modified_question(df, 16, 'return me the number of unique journals which have published papers')

inspect_row(df, 17)
insert_modified_question(df, 17, 'return me the number of unique papers presented on VLDB conference.')

inspect_row(df, 18)
insert_modified_question(df, 18, 'return me the number of unique papers published on the PVLDB journal after the year 2000.')

inspect_row(df, 19)
insert_modified_question(df, 19, 'return me the number of unique papers authored by H. V. Jagadish and presented at the VLDB conference after the year 2000.')

inspect_row(df, 20)
insert_modified_question(df, 20, 'return me the number of unique organizations in the domain of Databases located in North America.')

inspect_row(df, 21)
insert_modified_question(df, 21, 'return me the number of unique papers that are presented on VLDB conference and affliated with the University of Michigan.')

inspect_row(df, 22)
insert_modified_question(df, 22, 'return me the number of unique papers that are published in PVLDB journal after the year 2000 and affliated with the University of Michigan.')

inspect_row(df, 23)
insert_modified_question(df, 23, 'return me the total citations number of papers that are publisehd in PVLDB journal after the year 2005.')

---------------------
Question 16
Original Question: return me the number of journals which have papers by H. V. Jagadish .
Query: SELECT COUNT( DISTINCT ( JOURNALalias0.NAME ) ) FROM AUTHOR AS AUTHORalias0 , JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the number of unique journals which have published papers
---------------------
Question 17
Original Question: return me the number of papers on VLDB conference .
Query: SELECT COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) FROM CONFERENCE AS CONFERENCEalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE CONFERENCEalias0.NAME = "VLDB" AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID ;
Improved Question: return me the number of unique papers presented on VLDB conference.
---------------------
Question 18
Original Question: return me the number of papers on PVLDB after 2000 .
Query: SELECT COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) FROM JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.YEAR > 2000 ;
Improved Question: return me the number of unique papers published on the PVLDB journal after the year 2000.
---------------------
Question 19
Original Question: return me the number of papers by H. V. Jagadish on VLDB conference after 2000 .
Query: SELECT COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) FROM AUTHOR AS AUTHORalias0 , CONFERENCE AS CONFERENCEalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND CONFERENCEalias0.NAME = "VLDB" AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID AND PUBLICATIONalias0.YEAR > 2000 AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the number of unique papers authored by H. V. Jagadish and presented at the VLDB conference after the year 2000.
---------------------
Question 20
Original Question: return me the number of organizations in Databases area located in North America .
Query: SELECT COUNT( DISTINCT ( ORGANIZATIONalias0.NAME ) ) FROM AUTHOR AS AUTHORalias0 , DOMAIN AS DOMAINalias0 , DOMAIN_AUTHOR AS DOMAIN_AUTHORalias0 , ORGANIZATION AS ORGANIZATIONalias0 WHERE DOMAIN_AUTHORalias0.AID = AUTHORalias0.AID AND DOMAINalias0.DID = DOMAIN_AUTHORalias0.DID AND DOMAINalias0.NAME = "Databases" AND ORGANIZATIONalias0.CONTINENT = "North America" AND ORGANIZATIONalias0.OID = AUTHORalias0.OID ;
Improved Question: return me the number of unique organizations in the domain of Databases located in North America.
---------------------
Question 21
Original Question: return me the number of papers in VLDB conference in University of Michigan .
Query: SELECT COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) FROM AUTHOR AS AUTHORalias0 , CONFERENCE AS CONFERENCEalias0 , ORGANIZATION AS ORGANIZATIONalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE CONFERENCEalias0.NAME = "VLDB" AND ORGANIZATIONalias0.NAME = "University of Michigan" AND ORGANIZATIONalias0.OID = AUTHORalias0.OID AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the number of unique papers that are presented on VLDB conference and affliated with the University of Michigan.
---------------------
Question 22
Original Question: return me the number of papers in PVLDB after 2000 in University of Michigan .
Query: SELECT COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) FROM AUTHOR AS AUTHORalias0 , JOURNAL AS JOURNALalias0 , ORGANIZATION AS ORGANIZATIONalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND ORGANIZATIONalias0.NAME = "University of Michigan" AND ORGANIZATIONalias0.OID = AUTHORalias0.OID AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.YEAR > 2000 AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the number of unique papers that are published in PVLDB journal after the year 2000 and affliated with the University of Michigan.
---------------------
Question 23
Original Question: return me the total citations of papers in PVLDB in 2005 .
Query: SELECT SUM( PUBLICATIONalias0.CITATION_NUM ) FROM JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.YEAR = 2005 ;
Improved Question: return me the total citations number of papers that are publisehd in PVLDB journal after the year 2005.

In [7]:
# Wei

inspect_row(df, 24)
insert_modified_question(df, 24, 'return me the total number of citations for all papers published in the PVLDB journal before the year 2005.')

inspect_row(df, 25)
insert_modified_question(df, 25, 'return me the total number of citations received by papers published in the PVLDB journal each year.')

inspect_row(df, 26)
insert_modified_question(df, 26, 'return me the names of authors who are part of the same organization as H. V. Jagadish or Divesh Srivastava.')

inspect_row(df, 27)
insert_modified_question(df, 27, 'return me the titles of papers that were co-authored by H. V. Jagadish and Divesh Srivastava.')

inspect_row(df, 28)
insert_modified_question(df, 28, 'return me paper titles that were co-authored by H. V. Jagadish and Divesh Srivastava, which published before the year 2000.')

inspect_row(df, 29)
insert_modified_question(df, 29, 'return me the number of authors who have published more than 10 papers that include the keyword "Relational Database".')

inspect_row(df, 30)
insert_modified_question(df, 30, 'return me the number of journals, which have published more than 60 papers containing the keyword "Relational Database".')

inspect_row(df, 31)
insert_modified_question(df, 31, 'return me the number of keywords, which have been contained by more than 100 papers at the VLDB conference.')

---------------------
Question 24
Original Question: return me the total citations of papers in PVLDB before 2005 .
Query: SELECT SUM( PUBLICATIONalias0.CITATION_NUM ) FROM JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.YEAR < 2005 ;
Improved Question: return me the total number of citations for all papers published in the PVLDB journal before the year 2005.
---------------------
Question 25
Original Question: return me the total citations of papers in PVLDB in each year .
Query: SELECT PUBLICATIONalias0.YEAR , SUM( PUBLICATIONalias0.CITATION_NUM ) FROM JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND PUBLICATIONalias0.JID = JOURNALalias0.JID GROUP BY PUBLICATIONalias0.YEAR ;
Improved Question: return me the total number of citations received by papers published in the PVLDB journal each year.
---------------------
Question 26
Original Question: return me the authors who have cooperated with H. V. Jagadish or Divesh Srivastava .
Query: SELECT AUTHORalias0.NAME FROM AUTHOR AS AUTHORalias0 , AUTHOR AS AUTHORalias1 , ORGANIZATION AS ORGANIZATIONalias0 , ORGANIZATION AS ORGANIZATIONalias1 WHERE ( AUTHORalias1.NAME = "H. V. Jagadish" OR AUTHORalias1.NAME = "Divesh Srivastava" ) AND ORGANIZATIONalias0.OID = AUTHORalias0.OID AND ORGANIZATIONalias0.OID = AUTHORalias1.OID ;
Improved Question: return me the names of authors who are part of the same organization as H. V. Jagadish or Divesh Srivastava.
---------------------
Question 27
Original Question: return me the papers written by H. V. Jagadish and Divesh Srivastava .
Query: SELECT PUBLICATIONalias0.TITLE FROM AUTHOR AS AUTHORalias0 , AUTHOR AS AUTHORalias1 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 , WRITES AS WRITESalias1 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND AUTHORalias1.NAME = "Divesh Srivastava" AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID AND WRITESalias1.AID = AUTHORalias1.AID AND WRITESalias1.PID = PUBLICATIONalias0.PID ;
Improved Question: return me the titles of papers that were co-authored by H. V. Jagadish and Divesh Srivastava.
---------------------
Question 28
Original Question: return me the papers written by H. V. Jagadish and Divesh Srivastava before 2000 .
Query: SELECT PUBLICATIONalias0.TITLE FROM AUTHOR AS AUTHORalias0 , AUTHOR AS AUTHORalias1 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 , WRITES AS WRITESalias1 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND AUTHORalias1.NAME = "Divesh Srivastava" AND PUBLICATIONalias0.YEAR < 2000 AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID AND WRITESalias1.AID = AUTHORalias1.AID AND WRITESalias1.PID = PUBLICATIONalias0.PID ;
Improved Question: return me paper titles that were co-authored by H. V. Jagadish and Divesh Srivastava, which published before the year 2000.
---------------------
Question 29
Original Question: return me the number of authors who have more than 10 papers containing keyword Relational Database .
Query: SELECT COUNT( * ) FROM ( SELECT AUTHORalias0.NAME FROM AUTHOR AS AUTHORalias0 , KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 , WRITES AS WRITESalias0 WHERE KEYWORDalias0.KEYWORD = "Relational Database" AND PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID GROUP BY AUTHORalias0.NAME HAVING COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) > 10 ) AS DERIVED_TABLEalias0 ;
Improved Question: return me the number of authors who have published more than 10 papers that include the keyword "Relational Database".
---------------------
Question 30
Original Question: return me the number of journals, which have more than 60 papers containing keyword Relational Database .
Query: SELECT COUNT( * ) FROM ( SELECT JOURNALalias0.NAME FROM JOURNAL AS JOURNALalias0 , KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 WHERE KEYWORDalias0.KEYWORD = "Relational Database" AND PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID GROUP BY JOURNALalias0.NAME HAVING COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) > 60 ) AS DERIVED_TABLEalias0 ;
Improved Question: return me the number of journals, which have published more than 60 papers containing the keyword "Relational Database".
---------------------
Question 31
Original Question: return me the number of keywords, which have been contained by more than 100 papers in VLDB conference .
Query: SELECT COUNT( * ) FROM ( SELECT KEYWORDalias0.KEYWORD FROM CONFERENCE AS CONFERENCEalias0 , KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 WHERE CONFERENCEalias0.NAME = "VLDB" AND PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID GROUP BY KEYWORDalias0.KEYWORD HAVING COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) > 100 ) AS DERIVED_TABLEalias0 ;
Improved Question: return me the number of keywords, which have been contained by more than 100 papers at the VLDB conference.

In [8]:
# Rixin

inspect_row(df, 32)
insert_modified_question(df, 32, 'return me the number of publication keywords, which have been contained by more than 10 papers of author H. V. Jagadish.')

inspect_row(df, 33)
insert_modified_question(df, 33, 'return me the number of publication keywords, which have been contained by the most number of papers by author H. V. Jagadish.')

inspect_row(df, 34)
insert_modified_question(df, 34, 'return me the name of conferences, which have more than 10 papers by author H. V. Jagadish.')

inspect_row(df, 35)
insert_modified_question(df, 35, 'return me the name of conferences, which have the most number of papers by author H. V. Jagadish.')

inspect_row(df, 36)
insert_modified_question(df, 36, 'return me the name of journal, which have the most number of papers by author H. V. Jagadish.')

inspect_row(df, 37)
insert_modified_question(df, 37, 'return me the title of paper in the domain of "Databases" with the highest citation number.')

inspect_row(df, 38)
insert_modified_question(df, 38, 'return me the title of paper by author H. V. Jagadish with the highest citation number.')

inspect_row(df, 39)
insert_modified_question(df, 39, 'return me the title of paper after year 2000 in jounal PVLDB with the highest citation number.')

---------------------
Question 32
Original Question: return me the number of keywords, which have been contained by more than 10 papers of H. V. Jagadish .
Query: SELECT COUNT( * ) FROM ( SELECT KEYWORDalias0.KEYWORD FROM AUTHOR AS AUTHORalias0 , KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID GROUP BY KEYWORDalias0.KEYWORD HAVING COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) > 10 ) AS DERIVED_TABLEalias0 ;
Improved Question: return me the number of publication keywords, which have been contained by more than 10 papers of author H. V. Jagadish.
---------------------
Question 33
Original Question: return me the keyword, which have been contained by the most number of papers by H. V. Jagadish .
Query: SELECT KEYWORDalias0.KEYWORD FROM AUTHOR AS AUTHORalias0 , KEYWORD AS KEYWORDalias0 , PUBLICATION AS PUBLICATIONalias0 , PUBLICATION_KEYWORD AS PUBLICATION_KEYWORDalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATION_KEYWORDalias0.KID = KEYWORDalias0.KID AND PUBLICATIONalias0.PID = PUBLICATION_KEYWORDalias0.PID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID GROUP BY KEYWORDalias0.KEYWORD ORDER BY COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) DESC LIMIT 1 ;
Improved Question: return me the number of publication keywords, which have been contained by the most number of papers by author H. V. Jagadish.
---------------------
Question 34
Original Question: return me the conferences, which have more than 10 papers by H. V. Jagadish .
Query: SELECT CONFERENCEalias0.NAME FROM AUTHOR AS AUTHORalias0 , CONFERENCE AS CONFERENCEalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID GROUP BY CONFERENCEalias0.NAME HAVING COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) > 10 ;
Improved Question: return me the name of conferences, which have more than 10 papers by author H. V. Jagadish.
---------------------
Question 35
Original Question: return me the conference, which have the most number of papers by H. V. Jagadish .
Query: SELECT CONFERENCEalias0.NAME FROM AUTHOR AS AUTHORalias0 , CONFERENCE AS CONFERENCEalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.CID = CONFERENCEalias0.CID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID GROUP BY CONFERENCEalias0.NAME ORDER BY COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) DESC LIMIT 1 ;
Improved Question: return me the name of conferences, which have the most number of papers by author H. V. Jagadish.
---------------------
Question 36
Original Question: return me the journal, which have the most number of papers by H. V. Jagadish .
Query: SELECT JOURNALalias0.NAME FROM AUTHOR AS AUTHORalias0 , JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID GROUP BY JOURNALalias0.NAME ORDER BY COUNT( DISTINCT ( PUBLICATIONalias0.TITLE ) ) DESC LIMIT 1 ;
Improved Question: return me the name of journal, which have the most number of papers by author H. V. Jagadish.
---------------------
Question 37
Original Question: return me the paper in Databases area with the most citations .
Query: SELECT PUBLICATIONalias0.TITLE FROM DOMAIN AS DOMAINalias0 , DOMAIN_PUBLICATION AS DOMAIN_PUBLICATIONalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE DOMAINalias0.DID = DOMAIN_PUBLICATIONalias0.DID AND DOMAINalias0.NAME = "Databases" AND PUBLICATIONalias0.PID = DOMAIN_PUBLICATIONalias0.PID ORDER BY PUBLICATIONalias0.CITATION_NUM DESC LIMIT 1 ;
Improved Question: return me the title of paper in the domain of "Databases" with the highest citation number.
---------------------
Question 38
Original Question: return me the paper by H. V. Jagadish with the most citations .
Query: SELECT PUBLICATIONalias0.TITLE FROM AUTHOR AS AUTHORalias0 , PUBLICATION AS PUBLICATIONalias0 , WRITES AS WRITESalias0 WHERE AUTHORalias0.NAME = "H. V. Jagadish" AND WRITESalias0.AID = AUTHORalias0.AID AND WRITESalias0.PID = PUBLICATIONalias0.PID ORDER BY PUBLICATIONalias0.CITATION_NUM DESC LIMIT 1 ;
Improved Question: return me the title of paper by author H. V. Jagadish with the highest citation number.
---------------------
Question 39
Original Question: return me the paper after 2000 in PVLDB with the most citations .
Query: SELECT PUBLICATIONalias0.TITLE FROM JOURNAL AS JOURNALalias0 , PUBLICATION AS PUBLICATIONalias0 WHERE JOURNALalias0.NAME = "PVLDB" AND PUBLICATIONalias0.JID = JOURNALalias0.JID AND PUBLICATIONalias0.YEAR > 2000 ORDER BY PUBLICATIONalias0.CITATION_NUM DESC LIMIT 1 ;
Improved Question: return me the title of paper after year 2000 in jounal PVLDB with the highest citation number.

In [11]:
df.to_csv('masked_academic_sample_rewrite.csv')

In [9]:
csv_path = 'masked_academic_sample.csv'

df_csv = pd.read_csv(csv_path)
df_csv.head()

,question,db_id,db_path,masked,schema,update_schema,schema_dict
0,return me the year of Making database systems ...,academic,database/academic/academic.sqlite,return me the [MASK] of Making database system...,"\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","\nCREATE TABLE cite (\n\tcited INTEGER, \n\tci...","{'author': ['aid', 'homepage', 'name', 'oid'],..."
1,return me the papers after 2000 .,academic,database/academic/academic.sqlite,return me the papers after 2000 .,"\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","{'author': ['aid', 'homepage', 'name', 'oid'],..."
2,return me all the keywords .,academic,database/academic/academic.sqlite,return me all the [MASK] .,"\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","{'author': ['aid', 'homepage', 'name', 'oid'],..."
3,return me the references of Making database sy...,academic,database/academic/academic.sqlite,return me the [MASK] of Making database system...,"\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","\nCREATE TABLE cite (\n\tcited INTEGER, \n\tci...","{'author': ['aid', 'homepage', 'name', 'oid'],..."
4,return me the authors who have papers in VLDB ...,academic,database/academic/academic.sqlite,return me the [MASK] who have papers in VLDB [...,"\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","\nCREATE TABLE author (\n\taid INTEGER, \n\tho...","{'author': ['aid', 'homepage', 'name', 'oid'],..."